<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EvgenPC" name="Default test(failed)" tests="1" failures="1" timestamp="6 May 2013 16:04:20 GMT" time="0.031" errors="0">
  <testcase name="assertLoginPositive" time="0.013" classname="com.epam.ehalavachou.selenium.test.TestLoginPositive">
    <failure type="java.lang.AssertionError" message="test 1 not work! expected [test1] but found [test2]">
      <![CDATA[java.lang.AssertionError: test 1 not work! expected [test1] but found [test2]
	at com.epam.ehalavachou.selenium.test.TestLoginPositive.assertLoginPositive(TestLoginPositive.java:9)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- assertLoginPositive -->
</testsuite> <!-- Default test(failed) -->
