<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EvgenPC" name="Test" tests="3" failures="1" timestamp="6 May 2013 13:00:59 GMT" time="0.037" errors="0">
  <testcase name="assertTest2" time="0.012" classname="com.epam.ehalavachou.selenium.test.Test2"/>
  <testcase name="assertTest1" time="0.002" classname="com.epam.ehalavachou.selenium.test.Test1">
    <failure type="java.lang.AssertionError" message="test 1 not work! expected [test1] but found [test12]">
      <![CDATA[java.lang.AssertionError: test 1 not work! expected [test1] but found [test12]
	at com.epam.ehalavachou.selenium.test.Test1.assertTest1(Test1.java:9)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- assertTest1 -->
  <testcase name="assertTest3" time="0.001" classname="com.epam.ehalavachou.selenium.test.Test3"/>
</testsuite> <!-- Test -->
